### ISSUE TITLE
commutativity

### ISSUE THREAD

**Issue by juliangruber** [juliangruber/intersect#5]
@minuteman3:

> [...] both intersect and intersect.big are not commutative. Right now, when invoking intersect(a, b), regardless how many times an element x appears in b, x appears in the result set only as many times as it appears in a. In other words:

```js
intersect([2], [2,2,2])
[2]
```

```js
> intersect([2,2,2], [2])
[2,2,2]
```

> (the same is true of intersect.big)

**Comment by dominictarr** [comment]
If the inputs are really sets then the output will be too, if it has repeated items, it's not really a set.

**Comment by juliangruber** [comment]
good point, i'll update the documentation to say `sets` instead of arrays

**Comment by juliangruber** [comment]
do you think we can close this now?
